<?php

namespace Base\Forge\Entity;

use Base\Entity\User;
use Base\Forge\Enum\LicenseStatus;
use Base\Forge\Repository\LicenseRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * The right to download a licensed piece of software - and to install it
 * from the Composer repository. Granted when a LicenseOffer is paid for.
 *
 * The key is generated by its owner from their account and shown once:
 * only its SHA-256 is stored, plus a short prefix to recognise it by.
 */
#[ORM\Entity(repositoryClass: LicenseRepository::class)]
#[ORM\Table(name: 'forge_license')]
#[ORM\Index(name: 'forge_license_owner', columns: ['owner_id', 'status'])]
class License implements \Stringable
{
    #[ORM\Id, ORM\GeneratedValue, ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Software::class)]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')]
    private ?Software $software = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')]
    private ?User $owner = null;

    /** Null until the owner generates a key from their account. */
    #[ORM\Column(length: 64, unique: true, nullable: true)]
    private ?string $keyHash = null;

    #[ORM\Column(length: 12, nullable: true)]
    private ?string $keyPrefix = null;

    #[ORM\Column(length: 16, enumType: LicenseStatus::class)]
    private LicenseStatus $status = LicenseStatus::ACTIVE;

    #[ORM\Column]
    private int $seats = 1;

    /** Null: perpetual. */
    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?\DateTimeImmutable $expiresAt = null;

    /** Releases published after this date are not covered. Null: all of them. */
    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?\DateTimeImmutable $updatesUntil = null;

    /** The market order that paid for it, if any. */
    #[ORM\Column(length: 64, nullable: true)]
    private ?string $orderReference = null;

    #[ORM\Column(type: 'datetime_immutable')]
    private \DateTimeImmutable $createdAt;

    public function __construct(?Software $software = null, ?User $owner = null)
    {
        $this->software = $software;
        $this->owner = $owner;
        $this->createdAt = new \DateTimeImmutable();
    }

    public function __toString(): string
    {
        return ($this->software?->getName() ?? '').($this->keyPrefix ? ' · '.$this->keyPrefix.'…' : '');
    }

    public function getId(): ?int { return $this->id; }
    public function getSoftware(): ?Software { return $this->software; }
    public function setSoftware(Software $software): self { $this->software = $software; return $this; }
    public function getOwner(): ?User { return $this->owner; }
    public function setOwner(User $owner): self { $this->owner = $owner; return $this; }

    public function getKeyPrefix(): ?string { return $this->keyPrefix; }
    public function hasKey(): bool { return null !== $this->keyHash; }

    /** Stores the key's hash; the key itself is the caller's to show once. */
    public function setKey(string $key): self
    {
        $this->keyHash = hash('sha256', $key);
        $this->keyPrefix = substr($key, 0, 12);

        return $this;
    }

    public function matchesKey(string $key): bool
    {
        return null !== $this->keyHash && hash_equals($this->keyHash, hash('sha256', $key));
    }

    public function getStatus(): LicenseStatus { return $this->status; }
    public function setStatus(LicenseStatus $status): self { $this->status = $status; return $this; }

    public function getSeats(): int { return $this->seats; }
    public function setSeats(int $seats): self { $this->seats = max(1, $seats); return $this; }

    public function getExpiresAt(): ?\DateTimeImmutable { return $this->expiresAt; }
    public function setExpiresAt(?\DateTimeImmutable $expiresAt): self { $this->expiresAt = $expiresAt; return $this; }

    public function getUpdatesUntil(): ?\DateTimeImmutable { return $this->updatesUntil; }
    public function setUpdatesUntil(?\DateTimeImmutable $updatesUntil): self { $this->updatesUntil = $updatesUntil; return $this; }

    public function getOrderReference(): ?string { return $this->orderReference; }
    public function setOrderReference(?string $orderReference): self { $this->orderReference = $orderReference; return $this; }

    public function getCreatedAt(): \DateTimeImmutable { return $this->createdAt; }

    public function isValid(?\DateTimeImmutable $at = null): bool
    {
        $at ??= new \DateTimeImmutable();

        return LicenseStatus::ACTIVE === $this->status && (null === $this->expiresAt || $this->expiresAt > $at);
    }

    /** Whether this licence opens that release: valid, and the release within its updates. */
    public function covers(Release $release, ?\DateTimeImmutable $at = null): bool
    {
        if (!$this->isValid($at) || null === $this->software || $release->getSoftware() !== $this->software) {
            return false;
        }

        return null === $this->updatesUntil
            || null === $release->getPublishedAt()
            || $release->getPublishedAt() <= $this->updatesUntil;
    }
}
